### ISSUE TITLE
USB ESD protection not terminated to 5V

### ISSUE THREAD

**Issue by WillB97** [srobo/power-v4-hw#7]
The ESD chip used to protect the USB connection (U11) has it's VBUS connection connected to a GPIO pin rather than the USB's VBUS. As well as being the output for high voltage surges the VBUS pin is used for the termination pull-up, so only pulling up to 3.3V may cause the termination to not be correctly identified and make the connection more likely to fail with poorer cables.

This likely contributed to the USB cable issues seen at SP2019 where the Pi reset the ports while reporting EMI issues. This also affects the servo board.

**Comment by richardbarlow** [comment]
I don't think the STF202 uses steering diodes, so transients on D+/D- will not appear on its VBUS pin since each pin on the STF202 has its own dedicated TVS diode.

Also, I think the STF202 is a bit dubious as it tempts one into believing that it is usual to use VBUS as the pull up voltage source, but I believe this to be incorrect. The USB 2 spec (7.1.5.1) states that the pull up should be tied to a voltage source between 3.0V and 3.6V. It also states that the pull up voltage must be derived from or controlled by VBUS, which we can satisfy with firmware control (whether we do or not would need to be checked).

Ultimately, if there are issues with out-of-spec cables, the focus should be on the cables. We have definitely had issues the past with poor quality cables that resulted in us having to discard hundreds of them. The Startech ones appear to be of much higher quality. When we were investigating this I dismantled various cables to look at the quality of the termination in the plugs.

**Comment by richardbarlow** [comment]
I'm glad someone's looking at the designs though! They were done a long time ago and I'm sure there are some mistakes hidden in there somewhere.

**Comment by WillB97** [comment]
Indeed it looks like even OnSemi's own application notes are unsure about the STF202 VBUS voltage. The kits do seem to be rather more picky about their USB cables than other electronics, so I wonder whether we have something that is only marginally compliant or maybe just more recent ICs have better USB drivers than the STM32F103s.
